name: Build EXE

on:
  push:
    branches: [ master ]  # Only runs on master push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile CodeGUI.py
      - uses: actions/upload-artifact@v4  # Uploads EXE for later
        with:
          name: CodeGUI-exe
          path: dist/CodeGUI.exe