name: Build EXE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - run: pip install pyinstaller
      
      - run: pyinstaller --onefile --noconsole CodeGUI.py
      
      - name: Verify EXE exists
        shell: bash
        run: |
          if [ ! -f "dist/CodeGUI.exe" ]; then
            echo "::error::EXE file was not created!"
            ls -la dist/
            exit 1
          fi
          echo "EXE file exists:"
          ls -la dist/CodeGUI.exe
      
      - uses: actions/upload-artifact@v4
        with:
          name: codegui-exe
          path: dist/CodeGUI.exe
          retention-days: 7