name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*.*'      # Trigger only on version tags like v1.0.0
    branches:
      - master        # Only run if the tag is pushed from master branch
  workflow_dispatch:   # Optional: allow manual triggering

permissions:
  contents: write      # Needed for creating releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important to fetch all commits and tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile CodeGUI.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeGUI-exe
          path: dist/CodeGUI.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: CodeGUI-exe
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 Initial EXE Release!
            
            This release contains the compiled Windows `.exe` of CodeGUI.py.

            ✅ Built from the `master` branch.
            🏷️ Tag: `${{ github.ref_name }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
