name: Create Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: codegui-exe
          path: dist/

      - name: Verify download
        run: |
          if not (Test-Path -Path "dist\CodeGUI.exe" -PathType Leaf) {
            Write-Error "EXE file was not downloaded!"
            Get-ChildItem -Recurse
            exit 1
          }
          Write-Output "EXE file downloaded successfully:"
          Get-Item "dist\CodeGUI.exe"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/CodeGUI.exe"
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Version ${{ github.ref_name }}
            Built from master branch
          token: ${{ secrets.GITHUB_TOKEN }}