name: Create Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    needs: build
    runs-on: windows-latest
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: codegui-exe
          path: dist/
          
      - name: Verify downloaded EXE
        shell: bash
        run: |
          if [ ! -f "dist/CodeGUI.exe" ]; then
            echo "::error::Downloaded EXE file not found!"
            ls -la dist/
            exit 1
          fi
          echo "EXE file ready for release:"
          ls -la dist/CodeGUI.exe
          
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/CodeGUI.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Version ${{ github.ref_name }}
            Built from master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}