name: Create Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  # First job - independent (no dependencies)
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.value }}
    steps:
      - name: Extract tag name
        id: get_tag
        run: echo "value=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  # Second job - depends on prepare and downloads artifact
  release:
    needs: prepare
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: codegui-exe
          path: dist/
          
      - name: Verify downloaded EXE
        shell: bash
        run: |
          if [ ! -f "dist/CodeGUI.exe" ]; then
            echo "::error::Downloaded EXE file not found!"
            ls -la dist/
            exit 1
          fi
          echo "EXE file ready for release:"
          ls -la dist/CodeGUI.exe
          
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/CodeGUI.exe
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: Release ${{ needs.prepare.outputs.tag }}
          body: |
            Version ${{ needs.prepare.outputs.tag }}
            Built from master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}