name: Create Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          name: codegui-exe
          path: dist/
          
      - name: Verify EXE
        run: |
          ls -la dist/
          if [ ! -f "dist/CodeGUI.exe" ]; then
            echo "Error: EXE file not found!"
            exit 1
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/CodeGUI.exe
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}