name: Create Release

on:
  push:
    tags: [ 'v*' ]  # Only runs on version tags (v1, v2, etc.)

permissions:
  contents: write  # Needed for releases

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Download the EXE from the latest build
      - uses: actions/download-artifact@v4
        with:
          name: CodeGUI-exe
          path: dist/  # Places it in dist/CodeGUI.exe

      # Verify the file exists
      - run: ls -R dist/

      # Create the release
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/CodeGUI.exe
          name: Release ${{ github.ref_name }}
          body: |
            🎉 Release ${{ github.ref_name }}!
            This contains the compiled CodeGUI.exe.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}